strict-sigcheck = false

[YouTube]
enabled = true
brand = "YouTube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
changelog-keywords = ["YouTube"]
arch = "arm64-v8a"
version = "exp"

[YouTube.patches]
"github:MorpheApp/morphe-patches" = { version = "latest", exclude = ["Custom branding", "Enable debugging", "Disable play store updates"] }

[YT-Music]
enabled = true
brand = "YT-Music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
changelog-keywords = ["YouTube Music"]
arch = "arm64-v8a"
version = "exp"

[YT-Music.patches]
"github:MorpheApp/morphe-patches" = { version = "dev", exclude = ["Custom branding", "Enable debugging", "Disable play store updates"] }

[Reddit]
enabled = true
brand = "Reddit"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
version = "2026.29.0"
patcher-args = "-OindentLineColors1='#0066FF' -OindentLineColors2='#FF2E88' -OindentLineColors3='#9B5CFF' -OindentLineColors4='#2DE2E6' -OindentLineColors5='#FF5FA2' -OindentLineColors6='#FF8A3D' -OindentLineColors7='#FFD166' -OindentLineColors8='#3CFF7F'"

[Reddit.patches]
"github:MorpheApp/morphe-patches" = []
"github:jkennethcarino/adobo" = { version = "dev", include = ["Hide awards", "Disable home feed auto-refresh"], exclude = ["Hide post view counts", "Disable screenshot banner", "Open external links directly", "Remove ads and telemetry", "Sanitize share links"] }

[Twitter]
enabled = true
brand = "Twitter"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
changelog-keywords = ["Twitter"]
version = "auto"
arch = "arm64-v8a"

[Twitter.patches]
"github:crimera/piko" = { version = "dev", include = ["Browse tweet object", "Change version code"] }

[Instagram]
enabled = true
brand = "Instagram"
github-dlurl = "https://github.com/krvstek/uni-storage/releases/tag/instagram"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
changelog-keywords = ["Instagram"]
arch = "arm64-v8a"
patcher-args = "-e 'Clone' -OappName='Instagram'"

[Instagram.patches]
"github:crimera/piko" = { version = "dev", exclude = ["Change version code"] }

[Niagara-Launcher]
enabled = true
brand = "Niagara-launcher"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/mellowdrop-studio/niagara-launcher-%f0%9f%94%b9-fresh-clean/"
uptodown-dlurl = "https://niagara-launcher.en.uptodown.com/android"
version = "auto"

[Niagara-Launcher.patches]
"github:hoo-dles/morphe-patches" = { version = "dev", include = ["Hide app icon"] }
"github:MorpheApp/morphe-patches" = []

[Pinterest]
enabled = true
brand = "Pinterest"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/pinterest/pinterest-one-destination-for-a-world-of-inspiration"
uptodown-dlurl = "https://pinterest.en.uptodown.com/android"
changelog-keywords = ["Pinterest"]
version = "exp"
arch = "arm64-v8a"

[Pinterest.patches]
"github:browzomje/browzomje-patches" = { version = "dev" }
"github:MorpheApp/morphe-patches" = []

[Gboard]
enabled = true
brand = "Gboard"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard/"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
changelog-keywords = ["Gboard"]
version =  "auto"
arch = "arm64-v8a"

[Gboard.patches]
"github:jasonwu1994/Gboard-patches" = []
"github:jkennethcarino/adobo" = { version = "dev", include = ["Enable access points menu redesign", "Enable voice typing in incognito"], exclude = ["Always-incognito mode"] }

[Google-Photos]
enabled = true
brand = "GPhotos"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
version = "latest"
arch = "arm64-v8a"

[Google-Photos.patches]
"github:RookieEnough/De-Vanced" = []
